[general]
# Start Satty in fullscreen mode
fullscreen = false

# Exit directly after copy/save action
early-exit = true

# Draw corners of rectangles round if the value is greater than 0 (0 disables rounded corners)
corner-roundness = 12

# Select the tool on startup [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "brush"

# Configure the command to be called on copy, for example `wl-copy`
copy-command = "wl-copy"

# Increase or decrease the size of the annotations
annotation-size-factor = 2

# Filename to use for saving action. Omit to disable saving to file. Might contain format specifiers: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
# starting with 0.20.0, can contain leading tilde (~) for home directory
output-filename = "/tmp/screenshot-%Y-%m-%d_%H:%M:%S.png"

# After copying the screenshot, save it to a file as well
save-after-copy = true

# Hide toolbars by default
default-hide-toolbars = false

# Experimental (since 0.20.0): whether window focus shows/hides toolbars. This does not affect initial state of toolbars, see default-hide-toolbars.
focus-toggles-toolbars = true

# Fill shapes by default (since 0.20.0)
default-fill-shapes = false

# The primary highlighter to use, the other is accessible by holding CTRL at the start of a highlight [possible values: block, freehand]
primary-highlighter = "block"

# Disable notifications
disable-notifications = true

# Actions to trigger on right click (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-right-click = ["save-to-clipboard", "exit"]

# Actions to trigger on Enter key (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-enter = ["save-to-clipboard"]

# Actions to trigger on Escape key (order is important)
# [possible values: save-to-clipboard, save-to-file, exit]
actions-on-escape = ["exit"]

# Action to perform when the Enter key is pressed [possible values: save-to-clipboard, save-to-file]
# Deprecated: use actions-on-enter instead
action-on-enter = "save-to-clipboard"

# Right click to copy
# Deprecated: use actions-on-right-click instead
right-click-copy = false

# request no window decoration. Please note that the compositor has the final say in this. At this point. requires xdg-decoration-unstable-v1.
no-window-decoration = true

# experimental feature: adjust history size for brush input smooting (0: disabled, default: 0, try e.g. 5 or 10)
brush-smooth-history-size = 5

# Tool selection keyboard shortcuts (since 0.20.0)
[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "i"
arrow = "z"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "g"

# Font to use for text annotations
[font]
family = "Ubuntu Mono"
style = "Regular"

# Custom colours for the colour palette
[color-palette]
# These will be shown in the toolbar for quick selection
palette = [
    "#ea6962",
    "#3c3836",
    "#7DD3FC",
    "#F472B6",
    "#d8a657",
    "#a9b665",
    "#34D399",
]

# These will be available in the color picker as presets
# Leave empty to use GTK's default
custom = [
    "#F59E0B",
    "#a52a2a",
    "#dc143c",
    "#ff1493",
    "#ffd700",
    "#008000",
]